image: node:12
stages:
    - install
    - test
    - dast

install-dependencies:
    stage: install
    script:
        - npm install
    artifacts:
        expire_in: 1hr
        paths:
            - node_modules/
    cache:
        paths:
            - node_modules/
include:     
    - template: Code-Quality.gitlab-ci.yml              
include:
    - template: Container-Scanning.gitlab-ci.yml 
include:     
    - template: Dependency-Scanning.gitlab-ci.yml   
include:    
    - template: SAST.gitlab-ci.yml
test-apps:
    stage: test
    dependencies:
        - install-dependencies
    before_script:
        - apt-get upgrade && apt-get update
    script:
        - npm run test:ci 
include:
    - template: DAST.gitlab-ci.yml       

