version: "3.7"

services:
    backend_api:
      image: 'backend-api:latest'
      container_name: kod3rsstore_backend
      build:
        context: ./backend
        dockerfile: ./dockerfile
      command: /bin/sh -c "npm install && npm run dev"
      deploy:
        labels:
          - traefik.frontend.rule=Host:api.kod3rsstore.com
          - traefik.enable=true
          - traefik.port=3000
          - traefik.tags=traefik-public
          - traefik.docker.network=traefik-public
          - traefik.redirectorservice.frontend.entryPoints=http
          - traefik.redirectorservice.frontend.redirect.entryPoint=https
          - traefik.webservice.frontend.entryPoints=https
      networks:
        - traefik-public
        - default
networks:
  traefik-public:
    external: true
        
            
  
